// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZOQGEgGE8VciXK7IZfqjMh4rQFgaSCE',
    appId: '1:62280445884:web:270cd7425e14cfa3d805b9',
    messagingSenderId: '62280445884',
    projectId: 'portal-berita-4f8fc',
    authDomain: 'portal-berita-4f8fc.firebaseapp.com',
    storageBucket: 'portal-berita-4f8fc.appspot.com',
    measurementId: 'G-1XYNT4SKP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPj4Jjeq_7SI0-Vs-SnZacAooEUY6NF8',
    appId: '1:62280445884:android:19c2a351827b9b25d805b9',
    messagingSenderId: '62280445884',
    projectId: 'portal-berita-4f8fc',
    storageBucket: 'portal-berita-4f8fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lafm_0AwUy9_1sjAHmSQm32xDwYa-q0',
    appId: '1:62280445884:ios:515201565140bf3ed805b9',
    messagingSenderId: '62280445884',
    projectId: 'portal-berita-4f8fc',
    storageBucket: 'portal-berita-4f8fc.appspot.com',
    iosBundleId: 'com.example.beritaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lafm_0AwUy9_1sjAHmSQm32xDwYa-q0',
    appId: '1:62280445884:ios:515201565140bf3ed805b9',
    messagingSenderId: '62280445884',
    projectId: 'portal-berita-4f8fc',
    storageBucket: 'portal-berita-4f8fc.appspot.com',
    iosBundleId: 'com.example.beritaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZOQGEgGE8VciXK7IZfqjMh4rQFgaSCE',
    appId: '1:62280445884:web:5e8b9e0119e68de8d805b9',
    messagingSenderId: '62280445884',
    projectId: 'portal-berita-4f8fc',
    authDomain: 'portal-berita-4f8fc.firebaseapp.com',
    storageBucket: 'portal-berita-4f8fc.appspot.com',
    measurementId: 'G-15CTB5T73J',
  );

}